### ISSUE TITLE
The nav icons colors revert back to default white when changing screen from one page to another

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [thebylito/react-native-navigation-bar-color#12]
The nav icons colors revert back to default white when changing screen from one page to another. Couldn't fix this issue. Only happens when opening a screen and going back to old screen. 

I'm changing the background color from white to blue, therefore, when the background is white i'm setting it with the boolean to dark and making it white when changed into white screen.

**Comment by notmike101** [comment]
If I remember correctly, you need to set the colors again on each page.
Give that a try and get back to me.

**Comment by HarisSpahija** [comment]
Can we make an option to set a global value for all items that need to be configured?

**Comment by notmike101** [comment]
@HarisSpahija I'll look into it.  Make a new issue really quick?

**Comment by HarisSpahija** [comment]
@notmike101 See #14

**Comment by HarisSpahija** [comment]
This is issue can be closed due to a new issue on #14
