### ISSUE TITLE
Set global value for configuration

### ISSUE THREAD

**Issue by HarisSpahija** [thebylito/react-native-navigation-bar-color#14]
Related to #12

**Story:**
As a developer, I want to set a global value for the navigation-bar values so I do not have to specify it on each page

**Reason:**
Its a hassle to repeat the process of redefining the same value.

**Comment by notmike101** [comment]
Default color, or just maintain current color?

Which do you think would be better?

**Comment by HarisSpahija** [comment]
Default color, if you do not set a color it will go back to the default color. Thats basically how android already works on plain Java

**Comment by notmike101** [comment]
Makes sense, I'll see about having that implemented.
