### ISSUE TITLE
There isn't type file to support the typescript language (index.d.ts) 

### ISSUE THREAD

**Issue by davidgaspardev** [thebylito/react-native-navigation-bar-color#17]
To be able to import with the typescript language you need the type file (index.d.ts) to map the methods and variables that the library offers.

**Comment by notmike101** [comment]
TS support is out of the scope of this project.
If you'd like to create the type file and submit a merge request, I'd be more than happy to merge it in.

**Comment by thebylito** [comment]
#22 merged
