### ISSUE TITLE
transluctent navigation bar

### ISSUE THREAD

**Issue by Rondeveloper** [thebylito/react-native-navigation-bar-color#19]
How can I make the navigation bar transluctent ?
I tried setting the `changeNavigationBarColor('transparent);` but doing so makes the app crash.
Any ideas on how to achieve this?

**Comment by notmike101** [comment]
Try **#00000000**.
Let me know if it works.

Usually this is controlled by the theme you use for your app though.

**Comment by fabriziobertoglio1987** [comment]
@notmike101  I just tested this and it does not work

**Comment by fabriziobertoglio1987** [comment]
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.surfapp">

    <application
      android:theme="@style/AppTheme">
```

in android/app/src/main/res/values/styles.xml
```xml
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
      <item name="android:windowTranslucentStatus">true</item>
      <item name="android:windowTranslucentNavigation">true</item>
        <!-- Customize your theme here. -->
    </style>

</resources>
```

my react native component 
```javascript
  componentDidMount() {
    const color = '#00000000'
    changeNavigationBarColor(color);
  }

render() {
  return (
     <View styles={sytles.container} />
  )
}
const styles = StyleSheet.create({
  container: {
    flex: 1, 
    zIndex: 4, 
    backgroundColor: 'red', 
    height: Dimensions.get('screen').height,
  },
}
```

how you get the [full height of the screen in react native](https://stackoverflow.com/questions/46126521/android-navigation-bar-height-react-native?noredirect=1)

The [android solution](https://stackoverflow.com/questions/29069070/completely-transparent-status-bar-and-navigation-bar-on-lollipop)

<p align="center">
  <img src="https://user-images.githubusercontent.com/24992535/67348746-80f60c00-f578-11e9-9831-7d564a7bab4c.png" width="350">
</p>

**Comment by nikolowry** [comment]
@thebylito any chance of `changeNavigationBarColor` programmatically applying the translucent flag if the value of the `color` arg is set to `translucent`? 

Here's `react-native-onscreen-navbar-fork`'s implementation for reference https://github.com/seahorsepip/react-native-onscreen-navbar/blob/master/android/src/main/java/com/seapip/thomas/navigationbar/NavigationBarModule.java#L100

This is the only react-native Navigation Bar package that is actively maintained and `react-native-onscreen-navbar-fork` doesn't support changing the controls' colors -- it would be great if this feature was officially supported

**Comment by thebylito** [comment]
see #25
