### ISSUE TITLE
Getting null is not an object error with example code

### ISSUE THREAD

**Issue by GautierBlandin** [thebylito/react-native-navigation-bar-color#54]
As the title states it, even with the example code, I'm getting a null is not an object error. Any clue as to how to correct this problem ?

I'm running my project with Expo on a Poco X3.

**Comment by borijuyeong** [comment]
any clues?

**Comment by oleksii-jointoit** [comment]
for expo you can use another lib
expo-navigation-bar
https://docs.expo.dev/versions/latest/sdk/navigation-bar/
